### ISSUE TITLE
Export API Input Does Not Work

### ISSUE THREAD

**Issue by nytlag** [pentestfail/TA-Mixpanel#1]
Export API Input keeps failing with "HTTP Error 400: Bad Request" error. I've tested with Splunk vesions 7.2.3.x, 8.0, 8.1.x - all produce the same error. 

API Live and People work just fine. It only happens with Export API.

Are there specific changes that should be applied?

2021-06-23 17:51:41,533 DEBUG pid=28886 tid=MainThread file=connectionpool.py:_make_request:387 | "GET /servicesNS/nobody/TA-Mixpanel/storage/collections/data/TA_Mixpanel_checkpointer/mixpanel_export-test_export HTTP/1.1" 404 140
2021-06-23 17:51:41,534 INFO pid=28886 tid=MainThread file=base_modinput.py:log_info:293 | input_type=mixpanel_export input=test_export message='no checkpoint retrieved' last_day='2021-06-22' last_status='1624333901'
2021-06-23 17:51:42,124 ERROR pid=28886 tid=MainThread file=base_modinput.py:log_error:307 | input_type=mixpanel_export input=test_export message='An unknown error occurred!'
2021-06-23 17:51:42,125 ERROR pid=28886 tid=MainThread file=base_modinput.py:log_error:307 | Get error when collecting events.
Traceback (most recent call last):
  File "/opt/splunk/etc/apps/TA-Mixpanel/bin/ta_mixpanel/modinput_wrapper/base_modinput.py", line 127, in stream_events
    self.collect_events(ew)
  File "/opt/splunk/etc/apps/TA-Mixpanel/bin/mixpanel_export.py", line 68, in collect_events
    input_module.collect_events(self, ew)
  File "/opt/splunk/etc/apps/TA-Mixpanel/bin/input_module_mixpanel_export.py", line 96, in collect_events
    raise error
HTTPError: HTTP Error 400: Bad Request

**Comment by pentestfail** [comment]
This app has been archived from Splunkbase and is no longer maintained.  It is quite likely the Mixpanel API methods have changed altogether.

**Comment by rousdem-splunk** [comment]
Thank you for your feedback.
